# Generated by Django 3.2.11 on 2022-05-14 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(choices=[('java', 'java'), ('python', 'python'), ('PHP', 'PHP')], max_length=30)),
                ('duration', models.CharField(choices=[('2 months', '2 months'), ('3 months', '3 months'), ('6 months', '6 months')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('stid', models.IntegerField(primary_key=True, serialize=False)),
                ('stname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stuid', models.IntegerField(primary_key=True, serialize=False)),
                ('stuname', models.CharField(max_length=30)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studapp.course')),
            ],
        ),
    ]
