# Generated by Django 3.2.11 on 2022-05-14 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cname',
            new_name='course',
        ),
    ]
