# Generated by Django 3.2.11 on 2022-05-14 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0002_rename_cname_course_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='cid',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='studapp.course'),
        ),
    ]
