# Generated by Django 4.0.4 on 2022-05-19 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0003_staff_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.CharField(choices=[('2 hours', '2 hours'), ('3 hours', '3 hours'), ('6 hours', '6 hours')], max_length=30)),
                ('stid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studapp.staff')),
                ('stuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studapp.student')),
            ],
        ),
    ]
